-- Extended ML Analytics Schema
-- Adds tables for humor detection, question detection, NER, and user cards

-- =====================================================
-- HUMOR DETECTION RESULTS
-- =====================================================

CREATE TABLE IF NOT EXISTS ml_humor (
    message_id BIGINT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL,
    is_humorous BOOLEAN NOT NULL,
    humor_type VARCHAR(32),  -- 'joke', 'sarcasm', 'wordplay', 'irony', etc.
    score REAL NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ml_humor_chat
ON ml_humor(chat_id);

CREATE INDEX IF NOT EXISTS idx_ml_humor_is_humorous
ON ml_humor(chat_id, is_humorous) WHERE is_humorous = true;

COMMENT ON TABLE ml_humor IS
'Humor detection results for messages. Identifies jokes, sarcasm, and witty content.';

-- =====================================================
-- QUESTION DETECTION RESULTS
-- =====================================================

CREATE TABLE IF NOT EXISTS ml_questions (
    message_id BIGINT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL,
    is_question BOOLEAN NOT NULL,
    question_type VARCHAR(32),  -- 'factual', 'opinion', 'rhetorical', 'clarification', etc.
    score REAL NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ml_questions_chat
ON ml_questions(chat_id);

CREATE INDEX IF NOT EXISTS idx_ml_questions_is_question
ON ml_questions(chat_id, is_question) WHERE is_question = true;

COMMENT ON TABLE ml_questions IS
'Question detection results. Identifies questions and classifies their type.';

-- =====================================================
-- NAMED ENTITY RECOGNITION RESULTS
-- =====================================================

CREATE TABLE IF NOT EXISTS ml_ner (
    id BIGSERIAL PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL,
    entity_type VARCHAR(32) NOT NULL,  -- 'PERSON', 'ORG', 'LOC', 'MISC', etc.
    entity_text TEXT NOT NULL,
    start_pos INT,
    end_pos INT,
    confidence REAL NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ml_ner_message
ON ml_ner(message_id);

CREATE INDEX IF NOT EXISTS idx_ml_ner_chat
ON ml_ner(chat_id);

CREATE INDEX IF NOT EXISTS idx_ml_ner_entity_type
ON ml_ner(chat_id, entity_type);

-- Unique constraint to prevent duplicate entities for same message
CREATE UNIQUE INDEX IF NOT EXISTS idx_ml_ner_unique_entity
ON ml_ner(message_id, entity_type, entity_text, COALESCE(start_pos, -1));

COMMENT ON TABLE ml_ner IS
'Named Entity Recognition results. Multiple entities can be extracted per message.';

-- =====================================================
-- WEEKLY USER CARDS
-- =====================================================

CREATE TABLE IF NOT EXISTS ml_user_cards (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    stats_window_start DATE NOT NULL,
    stats_window_end DATE NOT NULL,
    stats JSONB NOT NULL,
    trends JSONB,
    daily_breakdown JSONB,
    messages_analyzed INT NOT NULL,
    card_version INT NOT NULL DEFAULT 1,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, chat_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_ml_user_cards_chat
ON ml_user_cards(chat_id);

CREATE INDEX IF NOT EXISTS idx_ml_user_cards_user
ON ml_user_cards(user_id);

CREATE INDEX IF NOT EXISTS idx_ml_user_cards_week
ON ml_user_cards(chat_id, week_start DESC);

-- For leaderboard queries (sorting by stats)
CREATE INDEX IF NOT EXISTS idx_ml_user_cards_stats_mood
ON ml_user_cards(chat_id, week_start, ((stats->'mood'->>'score')::numeric) DESC NULLS LAST);

COMMENT ON TABLE ml_user_cards IS
'Weekly aggregated user cards with stats, trends, and daily breakdown. Generated by card generator batch job.';

COMMENT ON COLUMN ml_user_cards.stats IS
'JSONB containing all computed stats: mood, volatility, toxicity, activity, reactions_received, chronotype, influence, humor';

COMMENT ON COLUMN ml_user_cards.trends IS
'JSONB containing trend comparisons between current week and previous week';

COMMENT ON COLUMN ml_user_cards.daily_breakdown IS
'JSONB array with per-day stats for the week';

COMMENT ON COLUMN ml_user_cards.stats_window_start IS
'Start of the 30-day rolling window used for stats calculation';

COMMENT ON COLUMN ml_user_cards.stats_window_end IS
'End of the 30-day rolling window (same as week_end)';
